[2022-05-18 23:02:37,549] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: model_level_dbt_great_expectations_dag.dbt_test.test.jaffle_shop.accepted_values_stg_jaffle_shop__orders_order_status__completed__shipped__returned__return_pending__placed.66bdbafd6b scheduled__2022-05-17T22:12:00.138285+00:00 [queued]>
[2022-05-18 23:02:37,672] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: model_level_dbt_great_expectations_dag.dbt_test.test.jaffle_shop.accepted_values_stg_jaffle_shop__orders_order_status__completed__shipped__returned__return_pending__placed.66bdbafd6b scheduled__2022-05-17T22:12:00.138285+00:00 [queued]>
[2022-05-18 23:02:37,674] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2022-05-18 23:02:37,678] {taskinstance.py:1242} INFO - Starting attempt 3 of 6
[2022-05-18 23:02:37,686] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-05-18 23:02:37,812] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): dbt_test.test.jaffle_shop.accepted_values_stg_jaffle_shop__orders_order_status__completed__shipped__returned__return_pending__placed.66bdbafd6b> on 2022-05-17 22:12:00.138285+00:00
[2022-05-18 23:02:37,862] {standard_task_runner.py:52} INFO - Started process 406 to run task
[2022-05-18 23:02:37,952] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'model_level_dbt_great_expectations_dag', 'dbt_test.test.jaffle_shop.accepted_values_stg_jaffle_shop__orders_order_status__completed__shipped__returned__return_pending__placed.66bdbafd6b', 'scheduled__2022-05-17T22:12:00.138285+00:00', '--job-id', '139', '--raw', '--subdir', 'DAGS_FOLDER/model_level_dbt_great_expectations_dag.py', '--cfg-path', '/tmp/tmpgq083wqe', '--error-file', '/tmp/tmpyd5hov2h']
[2022-05-18 23:02:37,959] {standard_task_runner.py:77} INFO - Job 139: Subtask dbt_test.test.jaffle_shop.accepted_values_stg_jaffle_shop__orders_order_status__completed__shipped__returned__return_pending__placed.66bdbafd6b
[2022-05-18 23:02:38,820] {logging_mixin.py:109} INFO - Running <TaskInstance: model_level_dbt_great_expectations_dag.dbt_test.test.jaffle_shop.accepted_values_stg_jaffle_shop__orders_order_status__completed__shipped__returned__return_pending__placed.66bdbafd6b scheduled__2022-05-17T22:12:00.138285+00:00 [running]> on host 3d7cb1bfa13d
[2022-05-18 23:02:39,335] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=luciano.naveiro
AIRFLOW_CTX_DAG_ID=model_level_dbt_great_expectations_dag
AIRFLOW_CTX_TASK_ID=dbt_test.test.jaffle_shop.accepted_values_stg_jaffle_shop__orders_order_status__completed__shipped__returned__return_pending__placed.66bdbafd6b
AIRFLOW_CTX_EXECUTION_DATE=2022-05-17T22:12:00.138285+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-17T22:12:00.138285+00:00
[2022-05-18 23:02:39,348] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-05-18 23:02:39,362] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'dbt --no-write-json test --target dev --select accepted_values_stg_jaffle_shop__orders_order_status__completed__shipped__returned__return_pending__placed --profiles-dir /opt/dbt/jaffle_shop --project-dir /opt/dbt/jaffle_shop']
[2022-05-18 23:02:39,640] {subprocess.py:85} INFO - Output:
[2022-05-18 23:05:24,470] {subprocess.py:89} INFO - 23:05:24  Running with dbt=1.1.0
[2022-05-18 23:05:27,485] {subprocess.py:89} INFO - 23:05:27  Found 5 models, 13 tests, 0 snapshots, 0 analyses, 170 macros, 0 operations, 0 seed files, 3 sources, 0 exposures, 0 metrics
[2022-05-18 23:05:27,653] {subprocess.py:89} INFO - 23:05:27
[2022-05-18 23:05:28,993] {subprocess.py:89} INFO - 23:05:28  Concurrency: 1 threads (target='dev')
[2022-05-18 23:05:29,027] {subprocess.py:89} INFO - 23:05:29
[2022-05-18 23:05:29,491] {subprocess.py:89} INFO - 23:05:29  1 of 1 START test accepted_values_stg_jaffle_shop__orders_order_status__completed__shipped__returned__return_pending__placed  [RUN]
[2022-05-18 23:05:34,411] {subprocess.py:89} INFO - 23:05:34  1 of 1 PASS accepted_values_stg_jaffle_shop__orders_order_status__completed__shipped__returned__return_pending__placed  [[32mPASS[0m in 4.92s]
[2022-05-18 23:05:34,613] {subprocess.py:89} INFO - 23:05:34
[2022-05-18 23:05:34,619] {subprocess.py:89} INFO - 23:05:34  Finished running 1 test in 6.95s.
[2022-05-18 23:05:34,646] {subprocess.py:89} INFO - 23:05:34
[2022-05-18 23:05:34,668] {subprocess.py:89} INFO - 23:05:34  [32mCompleted successfully[0m
[2022-05-18 23:05:34,687] {subprocess.py:89} INFO - 23:05:34
[2022-05-18 23:05:34,702] {subprocess.py:89} INFO - 23:05:34  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2022-05-18 23:05:37,563] {subprocess.py:93} INFO - Command exited with return code 0
[2022-05-18 23:05:39,438] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=model_level_dbt_great_expectations_dag, task_id=dbt_test.test.jaffle_shop.accepted_values_stg_jaffle_shop__orders_order_status__completed__shipped__returned__return_pending__placed.66bdbafd6b, execution_date=20220517T221200, start_date=20220518T230237, end_date=20220518T230539
[2022-05-18 23:05:40,186] {local_task_job.py:212} WARNING - State of this instance has been externally set to success. Terminating instance.
[2022-05-18 23:05:40,573] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 406
[2022-05-18 23:05:40,595] {taskinstance.py:1411} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-05-18 23:05:40,598] {subprocess.py:99} INFO - Sending SIGTERM signal to process group
[2022-05-18 23:05:40,606] {standard_task_runner.py:91} ERROR - Failed to execute job 139 for task dbt_test.test.jaffle_shop.accepted_values_stg_jaffle_shop__orders_order_status__completed__shipped__returned__return_pending__placed.66bdbafd6b
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/usr/local/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 225, in _capture_task_logs
    root_logger.setLevel(orig_level)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1354, in setLevel
    self.manager._clear_cache()
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1313, in _clear_cache
    logger._cache.clear()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1412, in signal_handler
    self.task.on_kill()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 193, in on_kill
    self.subprocess_hook.send_sigterm()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/subprocess.py", line 101, in send_sigterm
    os.killpg(os.getpgid(self.sub_process.pid), signal.SIGTERM)
ProcessLookupError: [Errno 3] No such process
[2022-05-18 23:05:41,887] {process_utils.py:66} INFO - Process psutil.Process(pid=406, status='terminated', exitcode=1, started='23:02:37') (406) terminated with exit code 1
