[2022-05-18 22:26:33,425] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: model_level_dbt_great_expectations_dag.ge_sources.sources.stripe__payment scheduled__2022-05-17T22:12:00.138285+00:00 [queued]>
[2022-05-18 22:26:33,452] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: model_level_dbt_great_expectations_dag.ge_sources.sources.stripe__payment scheduled__2022-05-17T22:12:00.138285+00:00 [queued]>
[2022-05-18 22:26:33,453] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2022-05-18 22:26:33,455] {taskinstance.py:1242} INFO - Starting attempt 8 of 11
[2022-05-18 22:26:33,457] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-05-18 22:26:33,493] {taskinstance.py:1262} INFO - Executing <Task(GreatExpectationsOperator): ge_sources.sources.stripe__payment> on 2022-05-17 22:12:00.138285+00:00
[2022-05-18 22:26:33,508] {standard_task_runner.py:52} INFO - Started process 240 to run task
[2022-05-18 22:26:33,566] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'model_level_dbt_great_expectations_dag', 'ge_sources.sources.stripe__payment', 'scheduled__2022-05-17T22:12:00.138285+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/model_level_dbt_great_expectations_dag.py', '--cfg-path', '/tmp/tmpljoa3t8t', '--error-file', '/tmp/tmpjhx8lwa0']
[2022-05-18 22:26:33,570] {standard_task_runner.py:77} INFO - Job 60: Subtask ge_sources.sources.stripe__payment
[2022-05-18 22:26:33,700] {logging_mixin.py:109} INFO - Running <TaskInstance: model_level_dbt_great_expectations_dag.ge_sources.sources.stripe__payment scheduled__2022-05-17T22:12:00.138285+00:00 [running]> on host 2c85119e8615
[2022-05-18 22:26:33,814] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=luciano.naveiro
AIRFLOW_CTX_DAG_ID=model_level_dbt_great_expectations_dag
AIRFLOW_CTX_TASK_ID=ge_sources.sources.stripe__payment
AIRFLOW_CTX_EXECUTION_DATE=2022-05-17T22:12:00.138285+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-17T22:12:00.138285+00:00
[2022-05-18 22:26:33,815] {great_expectations.py:122} INFO - Running validation with Great Expectations...
[2022-05-18 22:26:33,816] {great_expectations.py:125} INFO - Ensuring data context is valid...
[2022-05-18 22:26:36,476] {sqlalchemy_execution_engine.py:404} WARNING - schema_name specified creating a URL with schema is not supported. Set a default schema on the user connecting to your database.
[2022-05-18 22:26:36,488] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/great_expectations/datasource/data_connector/runtime_data_connector.py:135 DeprecationWarning: Specifying batch_identifiers as part of the RuntimeDataConnector config is deprecated as of v0.15.1 and will be removed by v0.18. Please configure batch_identifiers as part of Assets instead.
[2022-05-18 22:26:37,633] {validator.py:1669} INFO - 	24 expectation(s) included in expectation_suite.
[2022-05-18 22:26:37,946] {logging_mixin.py:109} WARNING - Calculating Metrics:   0%|          | 0/55 [00:00<?, ?it/s]
[2022-05-18 22:26:37,947] {logging_mixin.py:109} WARNING - Calculating Metrics:   0%|          | 0/55 [00:00<?, ?it/s]
[2022-05-18 22:26:37,963] {logging_mixin.py:109} WARNING - Calculating Metrics:   4%|3         | 2/55 [00:00<00:00, 129.50it/s]
[2022-05-18 22:26:38,057] {logging_mixin.py:109} WARNING - Calculating Metrics:   7%|7         | 4/55 [00:00<00:01, 36.49it/s] 
[2022-05-18 22:26:38,059] {logging_mixin.py:109} WARNING - Calculating Metrics:   7%|7         | 4/55 [00:00<00:01, 36.49it/s]
[2022-05-18 22:26:38,209] {logging_mixin.py:109} WARNING - Calculating Metrics:  35%|###4      | 19/55 [00:00<00:00, 77.78it/s]
[2022-05-18 22:26:38,211] {logging_mixin.py:109} WARNING - Calculating Metrics:  35%|###4      | 19/55 [00:00<00:00, 77.78it/s]
[2022-05-18 22:26:38,409] {util.py:247} WARNING - Using lossy conversion for decimal 1469.1666666666666667 to float object to support serialization.
[2022-05-18 22:26:38,410] {logging_mixin.py:109} WARNING - Calculating Metrics:  78%|#######8  | 43/55 [00:00<00:00, 100.93it/s]
[2022-05-18 22:26:38,412] {logging_mixin.py:109} WARNING - Calculating Metrics:  78%|#######8  | 43/55 [00:00<00:00, 100.93it/s]
[2022-05-18 22:26:38,515] {logging_mixin.py:109} WARNING - Calculating Metrics:  96%|#########6| 53/55 [00:00<00:00, 99.39it/s] 
[2022-05-18 22:26:38,516] {logging_mixin.py:109} WARNING - Calculating Metrics:  96%|#########6| 53/55 [00:00<00:00, 99.39it/s]
[2022-05-18 22:26:38,612] {logging_mixin.py:109} WARNING - Calculating Metrics:  98%|#########8| 54/55 [00:00<00:00, 99.39it/s]
[2022-05-18 22:26:38,678] {logging_mixin.py:109} WARNING - Calculating Metrics: 100%|##########| 55/55 [00:00<00:00, 99.39it/s]
[2022-05-18 22:26:38,733] {logging_mixin.py:109} WARNING - Calculating Metrics: 100%|##########| 55/55 [00:00<00:00, 99.39it/s]
[2022-05-18 22:26:38,735] {logging_mixin.py:109} WARNING - Calculating Metrics: 100%|##########| 55/55 [00:00<00:00, 69.86it/s]
[2022-05-18 22:26:38,737] {logging_mixin.py:109} WARNING - 
[2022-05-18 22:26:42,208] {great_expectations.py:197} INFO - Validation with Great Expectations successful.
[2022-05-18 22:26:42,216] {xcom.py:334} ERROR - Could not serialize the XCom value into JSON. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config.
[2022-05-18 22:26:42,217] {taskinstance.py:1703} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1517, in _execute_task
    self.xcom_push(key=XCOM_RETURN_KEY, value=result)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2262, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 67, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 100, in set
    value = XCom.serialize_value(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 331, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type CheckpointResult is not JSON serializable
[2022-05-18 22:26:42,262] {taskinstance.py:1280} INFO - Marking task as UP_FOR_RETRY. dag_id=model_level_dbt_great_expectations_dag, task_id=ge_sources.sources.stripe__payment, execution_date=20220517T221200, start_date=20220518T222633, end_date=20220518T222642
[2022-05-18 22:26:42,324] {standard_task_runner.py:91} ERROR - Failed to execute job 60 for task ge_sources.sources.stripe__payment
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1517, in _execute_task
    self.xcom_push(key=XCOM_RETURN_KEY, value=result)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2262, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 67, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 100, in set
    value = XCom.serialize_value(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 331, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type CheckpointResult is not JSON serializable
[2022-05-18 22:26:42,412] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-05-18 22:26:42,504] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
